{% set version = "1.9.3" %}
{% set variant = "openblas" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://github.com/numpy/numpy/archive/v{{ version }}.tar.gz
  sha256: c678dc4f7f4801a25c139c1131a97d9187cf645de276e1b3c74e2eadb5b5c961
  patches:
    - 11525.patch
    # customize gfortran executable that gets looked for to use our GFORTRAN env var
    - gfortran_alias.patch    # [linux]
    # fix fortran regex for ctng compilers
    - fortran_regex.patch     # [linux]
    # backport https://github.com/numpy/numpy/pull/7634 to support $CC
    - correct-c-compiler-customization-in-system_info.py.patch
    # port https://github.com/numpy/numpy/commit/e552922fe6c8854541337a10970ff1b62caffc70
    - fix-arrayterator-back_port_e552922.patch  # [py>=35]
    # fix needed to compile downstream packages on Linux with newer openblas
    - treat-openblas-as-c.patch  # [linux]
    # Apparently there is are a few bugs in terms of the reported
    # precision for long doubles on aarch64.
    - skip_test_longdouble.patch  # [aarch64]
    - skip_test_loss_of_precision_longcomplex.patch  # [aarch64]

build:
  number: 1207
  # We lack openblas on Windows, and therefore can't build numpy there either currently.
  skip: True  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - cython
    - python
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas

test:
  requires:
    - nose
  imports:
    - numpy
    - numpy.linalg.lapack_lite
  commands:
    - f2py -h

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'
  description: |
    NumPy is the fundamental package needed for scientific computing with Python.
  doc_url: https://docs.scipy.org/doc/numpy-1.9.0/reference/
  dev_url: https://github.com/numpy/numpy
  doc_source_url: https://github.com/numpy/numpy/tree/master/doc

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
    - mariusvniekerk
