{% set version = "1.20.2" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://github.com/numpy/numpy/releases/download/v{{ version }}/numpy-{{ version }}.tar.gz
  sha256: c049f410c78e76ffb0af830a8afbdf8baac09897b4152b97b1a3b8345ee338ff

build:
  number: 0
  skip: true  # [py<37]
  entry_points:
    - f2py = numpy.f2py.f2py2e:main  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - libblas
    - libcblas
    - liblapack
  run:
    - python

{% set tests_to_skip = "_not_a_real_test" %}
# Seems to fail with current version of blas for large numbers
# https://github.com/conda-forge/numpy-feedstock/pull/179#issuecomment-569591828
{% set tests_to_skip = tests_to_skip + " or test_sincos_float32" %}  # [linux64]
# Likely bugs in openblas????
# https://github.com/numpy/numpy/issues/14438#issuecomment-560940664
{% set tests_to_skip = tests_to_skip + " or test_einsum_sums_cfloat64" %}  # [ppc64le]
# Only the complex256 system is failing, but I don't know how to skip it on its own
# # https://github.com/numpy/numpy/issues/15243
{% set tests_to_skip = tests_to_skip + " or test_loss_of_precision" %}     # [ppc64le]
# Probably needs too much memory on ppc64le, it sometimes fails on travis
{% set tests_to_skip = tests_to_skip + " or test_large_zip" %}   # [ppc64le]
# Extra slow tests on aarch64 and ppc64le
{% set tests_to_skip = tests_to_skip + " or test_may_share_memory_easy_fuzz" %}   # [ppc64le or aarch64]
{% set tests_to_skip = tests_to_skip + " or test_may_share_memory_harder_fuzz" %}   # [ppc64le or aarch64]
{% set tests_to_skip = tests_to_skip + " or test_unary_ufunc_call_fuzz" %}   # [ppc64le or aarch64]
{% set tests_to_skip = tests_to_skip + " or test_count_nonzero_all" %}   # [ppc64le or aarch64]
{% set tests_to_skip = tests_to_skip + " or test_diophantine_fuzz" %}   # [ppc64le or aarch64]
{% set tests_to_skip = tests_to_skip + " or test_generalized_sq_cases" %}   # [ppc64le or aarch64]
{% set tests_to_skip = tests_to_skip + " or test_may_share_memory_harder_fuzz" %}   # [ppc64le or aarch64]
{% set tests_to_skip = tests_to_skip + " or test_large_zip" %}   # [ppc64le or aarch64]

test:
  requires:
    - pytest
    - pytest-xdist  # [aarch64]
    - hypothesis
    - setuptools
  commands:
    - f2py -h
    - export OPENBLAS_NUM_THREADS=1  # [unix]
    - set OPENBLAS_NUM_THREADS=1  # [win]
    - pytest --verbose --pyargs numpy -k "not ({{ tests_to_skip }})" --durations=0         # [not aarch64]
    - pytest -nauto --verbose --pyargs numpy -k "not ({{ tests_to_skip }})" --durations=0  # [aarch64]
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Array processing for numbers, strings, records, and objects.
  doc_url: https://docs.scipy.org/doc/numpy/reference/
  dev_url: https://github.com/numpy/numpy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
    - isuruf
    - xhochy
