{% set version = "1.9.3" %}
{% set variant = "openblas" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/numpy/numpy-{{ version }}.tar.gz
  sha256: c3b74d3b9da4ceb11f66abd21e117da8cf584b63a0efbd01a9b7e91b693fbbd6

build:
  number: 202
  # We lack openblas on Windows, and therefore can't build numpy there either currently.
  skip: True  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - cython
    - python
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*

test:
  requires:
    - nose
  imports:
    - numpy
    - numpy.linalg.lapack_lite
  commands:
    - f2py -h
    - conda inspect linkages -p $PREFIX numpy  # [not win]
    - conda inspect objects -p $PREFIX numpy  # [osx]

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
