{% set version = "1.21.0" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://github.com/numpy/numpy/releases/download/v{{ version }}/numpy-{{ version }}.tar.gz
  sha256: b662c841b29848c04d9134f31dbaa7d4c8e673f45bb3a5f28d02f49c424d558a
  patches:
    # carry numpy/numpy#19450 to help with flaky hypothesis errors
    - patches/0001-TST-Simplify-property-test.patch

build:
  number: 0
  skip: true  # [py<37]
  entry_points:
    - f2py = numpy.f2py.f2py2e:main  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - libblas
    - libcblas
    - liblapack
  run:
    - python
  run_constrained:
    # enforce eviction of package from anaconda defaults
    - numpy-base <0a0

{% set tests_to_skip = "_not_a_real_test" %}
# Seems to fail with current version of glibc for large numbers
# https://github.com/numpy/numpy/issues/15179
{% set tests_to_skip = tests_to_skip + " or test_sincos_float32" %}                    # [linux64]
# https://github.com/numpy/numpy/issues/15243
{% set tests_to_skip = tests_to_skip + " or test_loss_of_precision[complex256]" %}     # [ppc64le]
# Probably needs too much memory on ppc64le, it sometimes fails on travis
{% set tests_to_skip = tests_to_skip + " or test_large_archive or test_big_arrays" %}  # [ppc64le]
# the following skips are the longest running tests at time of writing; all over 45sec, up to 750sec
# skipping is done purely to stop pypy jobs from regularly timing out on drone/travis
{% if (aarch64 or ppc64le) and (python_impl == "pypy") %}
    {% set tests_to_skip = tests_to_skip + " or test_may_share_memory_easy_fuzz or test_may_share_memory_harder_fuzz"
                                         + " or test_binary_ufunc_1d_manual or test_diophantine_fuzz"
                                         + " or test_unary_ufunc_call_fuzz or test_unary_gufunc_fuzz"
                                         + " or test_big_arrays or test_large_archive or test_large_zip"
                                         + " or test_closing_fid or test_iter_buffered_reduce_reuse"
                                         + " or test_count_nonzero_all or test_divmod_128_64"
                                         + " or (test_generalized_sq_cases "
                                         + "     and (TestCond or TestDet or TestInv or TestSolve))" %}
{% endif %}

test:
  requires:
    - pytest
    - pytest-xdist  # [aarch64]
    - hypothesis
    - setuptools
  commands:
    - f2py -h
    # show SIMD features (some failures occur depending on presence/absence of e.g. AVX512)
    # change to np.show_config() for v>=1.22.0, cf. numpy/numpy#19130
    - python -c "import numpy; numpy._pytesttester._show_numpy_info()"
    {% set numproc = "-nauto" if aarch64 else "" %}
    - pytest --pyargs numpy -k "not ({{ tests_to_skip }})" {{ numproc }} --durations=100 -v
  imports:
    - numpy
    - numpy.core.multiarray
    - numpy.core._multiarray_tests
    - numpy.core.numeric
    - numpy.core._operand_flag_tests
    - numpy.core._struct_ufunc_tests
    - numpy.core._rational_tests
    - numpy.core.umath
    - numpy.core._umath_tests
    - numpy.linalg.lapack_lite
    - numpy.random.mtrand

about:
  home: http://numpy.scipy.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Array processing for numbers, strings, records, and objects.
  doc_url: https://docs.scipy.org/doc/numpy/reference/
  dev_url: https://github.com/numpy/numpy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
    - isuruf
    - xhochy
    - h-vetinari
