{% set version = "1.21.6" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://github.com/numpy/numpy/releases/download/v{{ version }}/numpy-{{ version }}.tar.gz
  sha256: d4efc6491a1cdc00f9eca9bf2c1aa13671776f6941c7321ddf75b45c862f0c2c
  patches:
    # carry numpy/numpy#19450 to help with flaky hypothesis errors
    - patches/0001-TST-Simplify-property-test.patch

build:
  number: 0
  skip: true  # [py<37]
  entry_points:
    - f2py = numpy.f2py.f2py2e:main  # [win]
  run_exports:
    - {{ pin_subpackage("numpy") }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - libblas
    - libcblas
    - liblapack
  run:
    - python
  run_constrained:
    # enforce eviction of package from anaconda defaults
    - numpy-base <0a0

{% set tests_to_skip = "_not_a_real_test" %}
# Seems to fail with current version of glibc for large numbers
# https://github.com/numpy/numpy/issues/15179
{% set tests_to_skip = tests_to_skip + " or test_sincos_float32" %}                             # [linux64]
# failure to raise FloatingPointError on osx for reciprocal
{% set tests_to_skip = tests_to_skip + " or test_unary_PyUFunc_O_O_method_full[reciprocal]" %}  # [osx]
# skip a test on pypy that expects GC behaviour
{% set tests_to_skip = tests_to_skip + " or (TestPickling and test_roundtrip)" %}               # [python_impl == "pypy"]
# there are some tests that cannot really work in emulation, see e.g. numpy/numpy#20445
{% set tests_to_skip = tests_to_skip + " or TestF77Mismatch" %}    # [build_platform != target_platform]
{% set tests_to_skip = tests_to_skip + " or Test_ARM_Features" %}  # [build_platform != target_platform]

test:
  requires:
    - pytest
    - pytest-timeout
    - pytest-xdist
    - hypothesis
    - setuptools
  commands:
    - f2py -h
    # numpy.test will show SIMD features of agent (in the past, there have been
    # failures that occured depending on presence/absence of e.g. AVX512);
    # for signature of numpy.test see the following (note default: label='fast'),
    # https://github.com/numpy/numpy/blob/maintenance/1.21.x/numpy/_pytesttester.py#L81-L82
    {% set label = "'fast'" if aarch64 else "'full'" %}
    {% set param = "verbose=1, label=" + label + ", tests=None" %}
    {% set extra = "extra_argv=['-k', 'not (" + tests_to_skip + ")', '-nauto', '--timeout=600', '--durations=50']" %}
    - python -c "import numpy, sys; sys.exit(not numpy.test({{ param }}, {{ extra }}))"  # [not ppc64le]
    # NOTE: test suite is skipped on ppc due to bugs in QEMU code that cause
    # CI to fail, even though the tests should run through on native hardware
  imports:
    - numpy
    - numpy.core.multiarray
    - numpy.core._multiarray_tests
    - numpy.core.numeric
    - numpy.core._operand_flag_tests
    - numpy.core._struct_ufunc_tests
    - numpy.core._rational_tests
    - numpy.core.umath
    - numpy.core._umath_tests
    - numpy.linalg.lapack_lite
    - numpy.random.mtrand

about:
  home: http://numpy.scipy.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Array processing for numbers, strings, records, and objects.
  doc_url: https://docs.scipy.org/doc/numpy/reference/
  dev_url: https://github.com/numpy/numpy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
    - isuruf
    - xhochy
    - h-vetinari
