{% set version = "1.11.0" %}

{% set variant = os.environ.get('BLAS_VARIANT', 'openblas') %}

package:
  name: numpy
  version: {{ version }}

source:
  fn: numpy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/numpy/numpy-{{ version }}.tar.gz
  md5: bc56fb9fc2895aa4961802ffbdb31d0b

build:
  script_env:
    - BLAS_VARIANT
  features:
    - blas_{{ variant }}

{# OPENBLAS #}
{% if variant == 'openblas' %}

  number: 200
  # We lack openblas on Windows, and therefore can't build numpy there either currently.
  skip: true  # [win]

requirements:
  build:
    - cython
    - python
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*

{# NOBLAS #}
{% elif variant == 'noblas' %}
  number: 100

requirements:
  build:
    - cython
    - python
    - setuptools
    - blas 1.0 {{ variant }}
  run:
    - python
    - blas 1.0 {{ variant }}
{% endif %}

test:
  requires:
    - nose
  commands:
    - f2py -h
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: array processing for numbers, strings, records, and objects.

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
