{% set version = "1.16.5" %}
{% set variant = "openblas" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://github.com/numpy/numpy/releases/download/v{{ version }}/numpy-{{ version }}.tar.gz
  sha256: 2b63c414fb43a4f0cb69b29b7e9d48275af0dbb5b1ffd2f2de99c4df9967e151
  patches:
    # Apparently not all glibcs have 128 bit precision floats implemented correctly.
    - skip_test_loss_of_precision.diff  # [aarch64 or ppc64le]
    - skip_test_mem_overlap.diff        # [aarch64]
    - skip_test_xerbla.diff             # [aarch64]
    - skip_test_einsum_cfloat64.diff    # [ppc64le]
    - skip_structured_object.diff       # [win and py27]
    - macos-lto-check.patch
    - backport_13558.patch

build:
  number: 1
  entry_points:
    - f2py = numpy.f2py.f2py2e:main  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    # gcc 7.3 segfaults on aarch64
    - clangdev    # [aarch64]
  host:
    - python
    - pip
    - cython
    - libblas
    - libcblas
    - liblapack
  run:
    - python

# Skipped test justificiation
# aarch64:
#   Timeouts: Marked as slow by numpy, extra slow due to QEMU
#       - test_unary_ufunc_call_fuzz
#       - test_may_share_memory_easy_fuzz
#       - test_may_share_memory_harder_fuzz
#       - test_large_zip 
#   Math: Qemu??? numpy bugs in BigEndian???
#       - test_loss_of_precision
#   We forget:
#       - test_xerbla_override
#       - test_sdot_bug_8577
# ppc64le
#   - test_loss_of_precision: likely a bug in libc/numpy
#   - test_einsum_sums_cfloat64: likely a bug in libc/numpy
test:
  requires:
    - pytest
    - pytest-timeout
  commands:
    - f2py -h
    - pytest --timeout=300 -v --pyargs numpy
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'
  doc_url: https://docs.scipy.org/doc/numpy/reference/
  dev_url: https://github.com/numpy/numpy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
