{% set version = "1.18.1" %}
{% set variant = "openblas" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://github.com/numpy/numpy/releases/download/v{{ version }}/numpy-{{ version }}.tar.gz
  sha256: e37802868ba5f389bf4e3f4c40c16e1b031814f0585ac122637de219de6279cb
  patches:
    - macos-lto-check.patch

build:
  number: 0
  skip: True  # [py27]
  entry_points:
    - f2py = numpy.f2py.f2py2e:main  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    # gcc 7.3 segfaults on aarch64
    - clangdev    # [aarch64]
  host:
    - python
    - pip
    - cython
    - libblas
    - libcblas
    - liblapack
  run:
    - python

# Skipped test justificiation
# aarch64:
#   Timeouts: Marked as slow by numpy, extra slow due to QEMU
#       - test_unary_ufunc_call_fuzz
#       - test_may_share_memory_easy_fuzz
#       - test_may_share_memory_harder_fuzz
#       - test_large_zip 
#   Math: Qemu??? numpy bugs in BigEndian???
#       - test_loss_of_precision
#   We forget:
#       - test_xerbla_override
#       - test_sdot_bug_8577
# ppc64le
#   - test_loss_of_precision: likely a bug in libc/numpy
#   - test_einsum_sums_cfloat64: likely a bug in libc/numpy
test:
  requires:
    - pytest
    - pytest-timeout
  commands:
    - f2py -h
    - pytest --timeout=300 -v --pyargs numpy -k "not (test_loss_of_precision or test_einsum_sums_cfloat64)"  # [ppc64le]
    - pytest --timeout=300 -v --pyargs numpy -k "not (test_loss_of_precision or test_may_share_memory_easy_fuzz or test_xerbla_override or test_may_share_memory_harder_fuzz or test_large_zip or test_sdot_bug_8577 or test_unary_ufunc_call_fuzz)"  # [aarch64]
    - pytest --timeout=300 -v --pyargs numpy  # [not (aarch64 or ppc64le)]
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'
  doc_url: https://docs.scipy.org/doc/numpy/reference/
  dev_url: https://github.com/numpy/numpy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
