{% set version = "1.22.3" %}

package:
  name: numpy
  version: {{ version }}

source:
  - url: https://github.com/numpy/numpy/releases/download/v{{ version }}/numpy-{{ version }}.tar.gz
    sha256: a906c0b4301a3d62ccf66d058fe779a65c1c34f6719ef2058f96e1856f48bca5
    patches:
      # backport fix for https://github.com/numpy/numpy/issues/20448
      - patches/0001-move-get_glibc_version-to-np.testing-skip-2-more-tes.patch
  # the sources by upstream themselves (as opposed to automated by github) contain the
  # svml submodule (which isn't in github tarball due to dear-github/dear-github#214);
  # keep this for reference & debugging when necessary; for exact commit, see:
  # https://github.com/numpy/numpy/tree/v{{ version }}/numpy/core/src/umath
  # - git_url: https://github.com/numpy/SVML.git
  #   git_rev: 1c5260a61e7dce6be48073dfa96291edb0a11d79
  #   folder: numpy/core/src/umath/svml

build:
  number: 2
  skip: true  # [py<38]
  entry_points:
    - f2py = numpy.f2py.f2py2e:main  # [win]
  run_exports:
    - {{ pin_subpackage("numpy") }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - setuptools <60.0.0                     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - setuptools <60.0.0
    - python
    - pip
    - cython
    - libblas
    - libcblas
    - liblapack
  run:
    - python
  run_constrained:
    # enforce eviction of package from anaconda defaults
    - numpy-base <0a0

{% set tests_to_skip = "_not_a_real_test" %}
# https://github.com/numpy/numpy/issues/15243
{% set tests_to_skip = tests_to_skip + " or test_loss_of_precision[complex256]" %}  # [ppc64le]
# there are some tests that cannot really work in emulation, see e.g. numpy/numpy#20445
{% set tests_to_skip = tests_to_skip + " or Test_ARM_Features" %}               # [build_platform != target_platform]
# flaky refcount-based test; already skipped upstream for win+py39
{% set tests_to_skip = tests_to_skip + " or test_partial_iteration_cleanup" %}  # [osx]


test:
  requires:
    - pytest
    - pytest-timeout
    - pytest-xdist         # [not ppc64le]
    - hypothesis
    - setuptools <60.0.0
    # some linux tests need a compiler
    - {{ compiler('c') }}  # [linux]
  commands:
    - f2py -h
    # numpy.test will show SIMD features of agent (in the past, there have been
    # failures that occured depending on presence/absence of e.g. AVX512);
    # for signature of numpy.test see the following (note default: label='fast'),
    # https://github.com/numpy/numpy/blob/maintenance/1.22.x/numpy/_pytesttester.py#L81-L82
    {% set label = "'fast'" if aarch64 else "'full'" %}
    {% set num_proc = "" if ppc64le else "'-nauto', " %}
    {% set param = "verbose=1, label=" + label + ", tests=None" %}
    {% set extra = "extra_argv=['-k', 'not (" + tests_to_skip + ")', " + num_proc + "'--timeout=3000', '--durations=50']" %}
    - python -c "import numpy, sys; sys.exit(not numpy.test({{ param }}, {{ extra }}))"
  imports:
    - numpy
    - numpy.core.multiarray
    - numpy.core._multiarray_tests
    - numpy.core.numeric
    - numpy.core._operand_flag_tests
    - numpy.core._struct_ufunc_tests
    - numpy.core._rational_tests
    - numpy.core.umath
    - numpy.core._umath_tests
    - numpy.linalg.lapack_lite
    - numpy.random.mtrand

about:
  home: http://numpy.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: The fundamental package for scientific computing with Python.
  doc_url: https://numpy.org/doc/stable/reference/
  dev_url: https://github.com/numpy/numpy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
    - isuruf
    - xhochy
    - h-vetinari
