{% set version = "1.13.3" %}
{% set variant = "openblas" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://github.com/numpy/numpy/releases/download/v{{ version }}/numpy-{{ version }}.tar.gz
  sha256: 4c6b4eef790528bebb7ec9590d74cc193868940fe68e4109a91c196df72d8094

  # since we want to run the test suite we need some files that are not in the sdist
  # url: https://github.com/numpy/numpy/archive/v{{ version }}.tar.gz
  # sha256: 1db97b12ea8f2ae5a8b847505f634dcd8c670ee311057ff5412a126becca45b8
  patches:
    # Apparently there is are a few bugs in terms of the reported
    # precision for long doubles on aarch64.
    # - skip_test_longdouble.patch  # [aarch64]
    - skip_test_loss_of_precision_longcomplex.patch  # [aarch64]
    - skip_warnings_tests_py37.patch

build:
  number: 1202
  # We lack openblas on Windows, and therefore can't build numpy there either currently.
  skip: True  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - python
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas

test:
  requires:
    - nose
  commands:
    - f2py -h
    - python {{ RECIPE_DIR }}/runtests_numpy.py --no-build
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
