{% set version = "1.18.2" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://github.com/numpy/numpy/releases/download/v{{ version }}/numpy-{{ version }}.tar.gz
  sha256: da204ce460aa4247e595b7c7189d2fb2ed5f796bc03197055de01dac61d0125e

build:
  number: 0
  skip: true  # [py27]
  entry_points:
    - f2py = numpy.f2py.f2py2e:main  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    # gcc 7.3 segfaults on aarch64
    - clangdev    # [aarch64]
  host:
    - python
    - pip
    - cython
    - libblas
    - libcblas
    - liblapack
  run:
    - python

{% set tests_to_skip = "_not_a_real_test" %}
# Seems to fail with current version of blas for large numbers
# https://github.com/conda-forge/numpy-feedstock/pull/179#issuecomment-569591828
{% set tests_to_skip = tests_to_skip + " or test_sincos_float32" %}  # [linux64]
# Not too sure why this is failing on aarch64 because harder_fuzz is passing
{% set tests_to_skip = tests_to_skip + " or test_may_share_memory_easy_fuzz" %}    # [aarch64]
# Likely bugs in openblas????
# https://github.com/numpy/numpy/issues/14438#issuecomment-560940664
{% set tests_to_skip = tests_to_skip + " or test_einsum_sums_cfloat64" %}  # [ppc64le]
# Only the complex256 system is failing, but I don't know how to skip it on its own
# # https://github.com/numpy/numpy/issues/15243
{% set tests_to_skip = tests_to_skip + " or test_loss_of_precision" %}     # [ppc64le or aarch64]
# Probably needs too much memory on ppc64le, it sometimes fails on travis
{% set tests_to_skip = tests_to_skip + " or test_large_zip" %}   # [ppc64le]

test:
  requires:
    - pytest
  commands:
    - f2py -h
    - pytest --verbose --pyargs numpy -k "not ({{ tests_to_skip }})"
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Array processing for numbers, strings, records, and objects.
  doc_url: https://docs.scipy.org/doc/numpy/reference/
  dev_url: https://github.com/numpy/numpy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
