{% set version = "1.15.4" %}
{% set variant = "openblas" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://github.com/numpy/numpy/releases/download/v{{ version }}/numpy-{{ version }}.tar.gz
  sha256: 766e09248298e3ad4ae4a805159f358610bbe7dcc7b4a14e5df2128c05655b80
  patches:
    - numpy_distutils_ldflags.diff

build:
  number: 1003

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libblas
    - libcblas
    - liblapack
    - python
    - pip
    - cython
  run:
    - python

test:
  requires:
    - pytest
  commands:
    - f2py -h
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'
  doc_url: https://docs.scipy.org/doc/numpy/reference/
  dev_url: https://github.com/numpy/numpy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
