{% set version = "1.22.0rc3" %}

package:
  name: numpy
  version: {{ version }}

source:
  - url: https://github.com/numpy/numpy/releases/download/v{{ version }}/numpy-{{ version }}.tar.gz
    sha256: 2a61da0dc062655097cefa5ae47712317b677f22bf3f20cf397c52fae57dea8a
    patches:
      # backport fix for https://github.com/numpy/numpy/issues/20448
      - patches/0001-move-get_glibc_version-to-np.testing-skip-2-more-tes.patch
  # include submodule (not in github tarball due to dear-github/dear-github#214), c.f.
  # https://github.com/numpy/numpy/tree/v{{ version }}/numpy/core/src/umath
  - git_url: https://github.com/numpy/SVML.git
    git_rev: 1c5260a61e7dce6be48073dfa96291edb0a11d79
    folder: numpy/core/src/umath/svml

build:
  number: 0
  skip: true  # [py<38]
  entry_points:
    - f2py = numpy.f2py.f2py2e:main  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - libblas
    - libcblas
    - liblapack
  run:
    - python
  run_constrained:
    # enforce eviction of package from anaconda defaults
    - numpy-base <0a0

{% set tests_to_skip = "_not_a_real_test" %}
# failure to raise FloatingPointError on osx for reciprocal
{% set tests_to_skip = tests_to_skip + " or test_unary_PyUFunc_O_O_method_full[reciprocal]" %}  # [osx]
# there are some tests that cannot really work in emulation, see e.g. numpy/numpy#20445
{% set tests_to_skip = tests_to_skip + " or TestF77Mismatch" %}    # [build_platform != target_platform]
{% set tests_to_skip = tests_to_skip + " or Test_ARM_Features" %}  # [build_platform != target_platform]

test:
  requires:
    - pytest
    - hypothesis
    - setuptools
    # some linux tests need a compiler
    - {{ compiler('c') }}  # [linux]
  commands:
    - f2py -h
    # numpy.test will show SIMD features of agent (in the past, there have been
    # failures that occured depending on presence/absence of e.g. AVX512)
    - python -c "import numpy, sys; sys.exit(not numpy.test(verbose=3, durations=50, extra_argv=['-k', 'not ({{ tests_to_skip }})']))"  # [not ppc64le]
    # NOTE: test suite is skipped on ppc due to bugs in QEMU code that cause
    # CI to fail, even though the tests should run through on native hardware
  imports:
    - numpy
    - numpy.core.multiarray
    - numpy.core._multiarray_tests
    - numpy.core.numeric
    - numpy.core._operand_flag_tests
    - numpy.core._struct_ufunc_tests
    - numpy.core._rational_tests
    - numpy.core.umath
    - numpy.core._umath_tests
    - numpy.linalg.lapack_lite
    - numpy.random.mtrand

about:
  home: http://numpy.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: The fundamental package for scientific computing with Python.
  doc_url: https://numpy.org/doc/stable/reference/
  dev_url: https://github.com/numpy/numpy

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
    - isuruf
    - xhochy
    - h-vetinari
