---
kind: pipeline
name: linux_aarch64_blas_implnetlibnumpy1_h3c1f4d213c

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_blas_implnetlibnumpy1.16python3.6.____cpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_blas_implnetlibnumpy1_h0225264c4c

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_blas_implnetlibnumpy1.16python3.7.____cpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_blas_implnetlibnumpy1_h34965a1288

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_blas_implnetlibnumpy1.16python3.8.____cpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_blas_implnetlibnumpy1_h8bf63f4331

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_blas_implnetlibnumpy1.18python3.6.____73_pypy
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_blas_implnetlibnumpy1_h736703fb78

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_blas_implnetlibnumpy1.19python3.7.____73_pypy
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_blas_implnetlibnumpy1_hb7b457c2db

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_blas_implnetlibnumpy1.19python3.9.____cpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_blas_implopenblasnump_h103a8fe7c7

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_blas_implopenblasnumpy1.16python3.6.____cpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_blas_implopenblasnump_hdf297ace58

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_blas_implopenblasnumpy1.16python3.7.____cpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_blas_implopenblasnump_h1a2447d65f

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_blas_implopenblasnumpy1.16python3.8.____cpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_blas_implopenblasnump_h4a82985706

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_blas_implopenblasnumpy1.18python3.6.____73_pypy
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_blas_implopenblasnump_h513a1feb5c

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_blas_implopenblasnumpy1.19python3.7.____73_pypy
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_blas_implopenblasnump_had1cd2bfc2

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_blas_implopenblasnumpy1.19python3.9.____cpython
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

