appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: native, linux_ppc64le: travis, win: azure}
travis:
  secure: {BINSTAR_TOKEN: HLa+fxAZIAOu1gLL1StsneYWwxaQ/ceiExLmHEfWaj/yQ7fj9RrryO/GcB1mIseaZT51ipGae88CYlm5hALGlhCIQd8TnMXNc5vdvEuMTbMXdd4BG4fLfv/q/NEHZ6hSJ08SgqAYmG5PTQ/Aoxi6kTnCwznJKKFYrpQF/rZnXZ5TfWqK57gR7OtzBuw9daWi//grP63aTP66jcmXwRYg97FmTSYgQ/9ZIx8MOwajgRCGU7u2HeYoR0Z4K21DcvJf+bOw2lhj3nmriyD7scYOY0zT1Qb/ZSQdSz+C3byzNm5PhSTaSJFfHPHV9PC41qeZc6m3cXqyGZwTvjby3OPFdfD/radpBuHJqwUVApYUdZCLsYbq3Vf83Hln0jA+QfKUiOqWd4CRg9HXu1iFA+mqKapGSkSgIWruEb7mdIt5DWYP1LEo1yvi2+o/PV7CvH4sMNnCt1F+CecDYou4JDoJzx7OmhgoAd+8Ez/n8mcIlv0M/DYUO059ZPTCHyX2g7LAAPOm6s4jYz1X0WJX216GkSlR2jqtCS+vRLNbWqR/DBwkXke33xsqs19ZkM4RYE5SwwuleUcpHM864WojP2BOZJr7BWJ7aaIX4u5dFuWovI6DZ8t7S9u46zZc6qGvVZpCiSIsAbn3Dmqvw0WLkP1Ikvpt6FfmZkofxwaM6hHUMJk=}
