travis:
  secure:
    BINSTAR_TOKEN: ov4nUdga5WNh9X38+KqfK6cIjp7P5w6iPTsvW9tBYeiUZDKBelwZXjDtAs7AUNxLkqn8QucpowWhgIF838/iTynvTqbNOgoW8p07oqHdfbIP3of7aZ4zC2gbGPka9wiCj25mrEbSn931THi5bHrmxgqFMA9QBbdiIN0yzEIE46VGnz674aCmjeH6SeqKCPY6N0j8gvFZMWcb6EDhJHo5HnluluIR9V6sTJwlU5KRuUk+YTUaRg3brWjzQbLPE5WYZMdtwQNgAMyuYW1ly4vMy2f2acwJmfpSDlxMbarAhtO7QjZ3oPWMrbBf7qCeyAmp9chP078EPLXPAVDMUZkiAbOkLDOqAMQbV98rycFnN8/SbGlNhsUdaUAMjYbJOBiwH27JA39q8LPWH77MVQhQkSKHiOFXQoDFguCP8BI4Nz1wwf8G+bBxSzsnTRY2iCDSizMu3w+cHgWUTx7Mb/vVBHQMVnwriwInEWSA7QfIX1HAdTe3p22o5FZDKZFJK4uyoGKXM8Y9Ld6YpJ4LvT+/AZOxoEDt4mye//UOMRsQBx7/KE/l8zMuIFvDWLFTUZVJJaB5d2wvPrYl4B7beh1Js2L2GHgtI8b4Z6zEp3j1lvzhpwilvvIJ/T6aBIR8pzvWuMffAj4dfCsF+tvcinT0Nt4IZM+vDNqsb+DIyGfax7w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'